conf: Remove `-ansi` from KBUILD_HOSTCFLAGS for cygwin
This is causing the following compiling error when building u-boot within cygwin:

```
scripts/kconfig/conf.c:562:9: error: C++ style comments are not allowed in ISO C90
  562 |         //zconfdump(stdout);
```

Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>